export const CREATE_QUIZ_CATEGORY_REQUEST = 'CREATE_QUIZ_CATEGORY_REQUEST';
export const CREATE_QUIZ_CATEGORY_SUCCESS = 'CREATE_QUIZ_CATEGORY_SUCCESS';
export const CREATE_QUIZ_CATEGORY_FAILED = 'CREATE_QUIZ_CATEGORY_FAILED';


export const GET_QUIZ_CATEGORY_REQUEST = 'GET_QUIZ_CATEGORY_REQUEST';
export const GET_QUIZ_CATEGORY_SUCCESS = 'GET_QUIZ_CATEGORY_SUCCESS';
export const GET_QUIZ_CATEGORY_FAILED = 'GET_QUIZ_CATEGORY_FAILED';


export const GET_QUIZ_CATEGORY_BY_ID_REQUEST = 'GET_QUIZ_CATEGORY_BY_ID_REQUEST';
export const GET_QUIZ_CATEGORY_BY_ID_SUCCESS = 'GET_QUIZ_CATEGORY_BY_ID_SUCCESS';
export const GET_QUIZ_CATEGORY_BY_ID_FAILED = 'GET_QUIZ_CATEGORY_BY_ID_FAILED';

export const UPDATE_QUIZ_CATEGORY_BY_ID_REQUEST = 'UPDATE_QUIZ_CATEGORY_BY_ID_REQUEST';
export const UPDATE_QUIZ_CATEGORY_BY_ID_SUCCESS = 'UPDATE_QUIZ_CATEGORY_BY_ID_SUCCESS';
export const UPDATE_QUIZ_CATEGORY_BY_ID_FAILED = 'UPDATE_QUIZ_CATEGORY_BY_ID_FAILED';

export const DELETE_QUIZ_CATEGORY_BY_ID_REQUEST = 'DELETE_QUIZ_CATEGORY_BY_ID_REQUEST';
export const DELETE_QUIZ_CATEGORY_BY_ID_SUCCESS = 'DELETE_QUIZ_CATEGORY_BY_ID_SUCCESS';
export const DELETE_QUIZ_CATEGORY_BY_ID_FAILED = 'DELETE_QUIZ_CATEGORY_BY_ID_FAILED';
