export const POST_ADMIN_SIGNIN_REQUEST = 'POST_ADMIN_SIGNIN_REQUEST';
export const POST_ADMIN_SIGNIN_SUCCESS = 'POST_ADMIN_SIGNIN_SUCCESS';
export const POST_ADMIN_SIGNIN_FAILED = 'POST_ADMIN_SIGNIN_FAILED';
